version: "3.9"
services:
  flask:
    build: .
    environment:
      - FLASK=app.py # основное приложение
      - FLASK_DEBUG=1 
      - PYTHONUNBUFFERED=True
    # command: flask run --host=0.0.0.0 # для эксперименттов только 
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app --reload # в проде вот это нужно уже
    ports:
      - "5000:5000"
    volumes:
      - ./:/root